# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    # Let's go check on the install.
    # Excellent! It's done.
    # And the message is right on: it says we need to get to work in the new config file: liip_imagine.yaml.
    # Go open that: config/packages/liip_imagine.yaml.
    # Uncomment the root key to activate the bundle,
    # leave the driver alone - it defaults to gd -
    # and uncomment filter_sets.
    filter_sets:
        cache: ~
        # Let's create our first filter set called squared_thumbnail_small.
        # We'll use this on the homepage to reduce the images down to 100 by 100.
        # To do that, uncomment the filters key
        # and I'll copy the thumbnail example from below,
        # move it up here, and uncomment it.
        squared_thumbnail_small:
            filters:
                thumbnail:
                    # Set the size to 200 by 200 so it looks good on Retina displays.
                    # The mode: outbound is how the thumbnail is applied - you can also use inbound.
                    size: [200, 200]
                    mode: outbound
                    allow_upscale: true
        # Let's render a thumbnail on the show page too.
        # The size here is restricted to a width of 250.
        # Copy the first filter, paste,
        # and call this one, how about, squared_thumbnail_medium.
        # Set the size to 500 by 500.
        squared_thumbnail_medium:
            filters:
                thumbnail:
                    size: [500, 500]
                    mode: outbound
                    allow_upscale: true
    # Let's go to back to the LiipImagineBundle documentation:
    # find their GitHub page and then click down here on the "Download the Bundle"
    # link as an easy way to get into their full docs.
    # Now, go back to the main page and down here near the bottom,
    # it talks about different "data loaders".
    # The default is "File System", we want Flysystem.
    # Let's see, we've already installed the bundle.
    # Copy this loaders section - we already have our Flysystem config all set up.
    # Then, open our liip_imagine.yaml file and, really, anywhere, paste!
    # This creates a loader called profile_photos - that name can be anything.
    # Let's use flysystem_loader.
    # The critical part is the key flysystem:
    # that says to use the "Flysystem" loader that comes with the bundle.
    # The only thing it needs to know, is the service id of the filesystem that we want to use.
    loaders:
        flysystem_loader:
            # For that, go back to config/services.yaml and copy the long service id from the bind section.
            # Back in liip_imagine.yaml, paste!
            flysystem:
                # We reference this in a few spots.
                # In liip_imagine.yaml, take out the public_ in these two spots.
                filesystem_service: oneup_flysystem.uploads_filesystem_filesystem
    # We now have a "loader" called flysystem_loader,
    # and a "loader's" job is to "load" the source file.
    # You can technically have multiple loaders, though I've never had to do that.
    # To always have LiipImagineBundle load the files via Flysystem,
    # below, add data_loader set to the loader's name: flysystem_loader.
    # I'll add a comment: “default loader to use for all filter sets”
    # default loader to use for all filter sets
    data_loader: flysystem_loader
    # Because, you can technically specify which loader you want to use on each filterset.
    # Again, I've never had to do that: we always want to use flysystem.
    # Cool! Let's try it! Go into the public/ directory and delete all the existing thumbnails -
    # let's delete media/cache/ entirely.
    # By doing this, the bundle will use the data loader to get the contents of each image
    # so that it can recreate the thumbnails.
    # So, the "data loader" is responsible for reading the original image.
    # But, there's another important concept from LiipImagineBundle called "resolvers".
    # Click down on the "Flysystem Resolver" in their docs.
    # The resolver is responsible for saving the thumbnail image back to the filesystem after all of the transformations.
    # By default, no surprise, LiipImagineBundle writes things directly to the filesystem.
    # So even if we moved Flysystem to s3,
    # LiipImagineBundle would still be writing the thumbnail files back to our server - into the public/media directory.
    # Tip: You can also completely offload the processing and storage of your files to a cloud service like rokka.io by leveraging LiipRokkaImagineBundle.
    # Let's change that! In the docs, copy the resolvers section.
    # Back in our liip_imagine.yaml file, paste that.
    # It's pretty much the same as before:
    # we'll call it flysystem_resolver
    # and tell it to save the images using the same filesystem service.
    # Remove visibility - that sets the Flysystem visibility,
    # which is a concept we'll talk about soon.
    # True is the default value anyways,
    # which basically means these files will be publicly accessible.
    resolvers:
        flysystem_resolver:
            flysystem:
                filesystem_service: oneup_flysystem.uploads_filesystem_filesystem
                # cache_prefix is the subdirectory within the filesystem
                # where the files should be stored and root_url is the URL
                # that all the paths will be prefixed with when the image paths are rendered.
                # Right now, it needs to be /uploads.
                # For example, if LiipImagineBundle stores a file called media/cache/foo.jpg into Flysystem,
                # we know that the public path to this will be /uploads/media/cache/foo.jpg.
                # We'll talk more about this setting later when we move to s3.
                cache_prefix: media/cache
                # Thanks to these, we can do some cleanup! In liip_imagine.yaml, we need the URL. Copy
                # uploads_base_url and then use %uploads_base_url%.
                root_url: '%uploads_base_url%'
    # Ok, delete the media/ directory entirely.
    # Oh, and I almost forgot the last step:
    # add cache set to flysystem_resolver - let's put an "r" on that.
    # default cache resolver for saving thumbnails
    cache: flysystem_resolver
    # This tells the bundle to always use this resolver.
    # I'm not sure why it's called "cache" - the bundle seems to use "resolver" and "cache" to describe this one concept.
    # Ok! Moment of truth! Refresh. Ha! It works! Go check out where the thumbnails are stored: there
    # is no media/ directory anymore! The Flysystem filesystem points to the public/uploads
    # directory, so the media/cache directory lives there. And thanks to the /uploads root_url,
    # when it renders the path, it knows to start with /uploads and then the path in Flysystem.
    # I love this! It's a bit tricky to get these two libraries to play together perfectly. But now we are much
    # more prepared to switch between local uploads and S3.
    # Next: we can generate public URLs to thumbnailed files or the original files. But, what if you need
    # to force all the URLs to include the domain name? This is something you don't think about until
    # you need to generate a PDF or send an email from a console command or worker. Then... it can
    # be a nightmare. Let's add this to our asset system in a way that we love.