framework:
    messenger:
        failure_transport: failed
        transports:
            # https://symfony.com/doc/current/messenger.html#transports
            async:
                dsn: 'doctrine://default?queue_name=async'
                retry_strategy:
                    delay: 500
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        routing:
            # Route your messages to the transports
            'App\Message\AddPonkaToImage': async
            'App\Message\DeletePhotoFile': async
        buses:
            messenger.bus.default:
                middleware:
                    - App\Messenger\AuditMiddleware