# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/blob/release/3.x/Resources/doc/index.md
# While Jordi is preparing our packages, go back to their docs.
# Flysystem has two important concepts,
# which you can see here in the config example.
# First, we need to set up an "adapter",
# which is a lower-level object.
# Give it any name - like my_adapter.
# Then, this key - local - is the critical part:
# this says that you want to use the local adapter -
# an adapter that stores things on the local filesystem.
# Click the AwsS3 adapter link.
# If you want to use this adapter and store your files in S3,
# you'll use the key awss3v3.
# Every adapter also has different options.
# We're going to start with the local adapter,
# but move to s3 later.
# But the real star, is the filesystem.
# Same thing: you give it any nickname, like my_filesystem
# and then say: this filesystem uses the my_adapter adapter.
# We'll talk about visibility later.
# The filesystem is the object that we'll work with directly to read, write & delete files.
# Ok, go check on Composer.
# It's done and thanks to the recipe,
# we have a new config/packages/oneup_flysystem.yaml file with the same config we just saw in the docs.
# Let's create 1 adapter and 1 filesystem for our uploads.
# Call the adapter, how about, public_uploads_adapter.
# I'm saying "public uploads" because this will put things into the public/ directory:
# they will be publicly accessible.
# We'll talk about private uploads soon -
# those are files where you need to do some security checks before you allow a user to see them.
# Change the directory to %kernel.project_dir% and then /public/uploads.
# Tip: If you're using version 4 of oneup/flysystem-bundle,
# the directory config is now called location.
oneup_flysystem:
    adapters:
        public_uploads_adapter:
            local:
                directory: '%kernel.project_dir%/public/uploads'
        default_adapter:
            local:
                directory: '%kernel.cache_dir%/flysystem'
    # That is the root of this filesystem:
    # everything will be stored relative to this.
    # Give the filesystem a similar name - public_uploads_filesystem - and set adapter: to public_uploads_adapter.
    filesystems:
        public_uploads_filesystem:
            adapter: public_uploads_adapter
        default_filesystem:
            adapter: default_adapter
            alias: League\Flysystem\Filesystem
