# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/blob/release/3.x/Resources/doc/index.md
# While Jordi is preparing our packages, go back to their docs.
# Flysystem has two important concepts,
# which you can see here in the config example.
# First, we need to set up an "adapter",
# which is a lower-level object.
# Give it any name - like my_adapter.
# Then, this key - local - is the critical part:
# this says that you want to use the local adapter -
# an adapter that stores things on the local filesystem.
# Click the AwsS3 adapter link.
# If you want to use this adapter and store your files in S3,
# you'll use the key awss3v3.
# Every adapter also has different options.
# We're going to start with the local adapter,
# but move to s3 later.
# But the real star, is the filesystem.
# Same thing: you give it any nickname, like my_filesystem
# and then say: this filesystem uses the my_adapter adapter.
# We'll talk about visibility later.
# The filesystem is the object that we'll work with directly to read, write & delete files.
# Ok, go check on Composer.
# It's done and thanks to the recipe,
# we have a new config/packages/oneup_flysystem.yaml file with the same config we just saw in the docs.
# Let's create 1 adapter and 1 filesystem for our uploads.
# Call the adapter, how about, public_uploads_adapter.
# I'm saying "public uploads" because this will put things into the public/ directory:
# they will be publicly accessible.
# We'll talk about private uploads soon -
# those are files where you need to do some security checks before you allow a user to see them.
# Change the directory to %kernel.project_dir% and then /public/uploads.
# Tip: If you're using version 4 of oneup/flysystem-bundle,
# the directory config is now called location.
oneup_flysystem:
    adapters:
        public_uploads_adapter:
            local:
                # Next, in oneup_flysystem.yaml, we need the directory name. Copy the other parameter:
                # %uploads_dir_name%.
                directory: '%kernel.project_dir%/public/%uploads_dir_name%'
    # That is the root of this filesystem:
    # everything will be stored relative to this.
    # Give the filesystem a similar name - public_uploads_filesystem - and set adapter: to public_uploads_adapter.
    # What about this alias key?
    # Let's see what that does.
    # First, when you configure a filesystem here, it creates a service.
    # Find your terminal and run:
    # php bin/console debug:container flysystem
    # Select one of the following services to display its information:
    #     [0 ] liip_imagine.binary.loader.prototype.flysystem
    #     [1 ] liip_imagine.binary.loader.prototype.flysystem2
    #     [2 ] liip_imagine.cache.resolver.prototype.flysystem
    #     [3 ] liip_imagine.cache.resolver.prototype.flysystem2
    #     [4 ] oneup_flysystem.adapter_factory.local
    #     [5 ] oneup_flysystem.adapter_factory.nulladapter
    #     [6 ] oneup_flysystem.adapter_factory.zip
    #     [7 ] oneup_flysystem.adapter_factory.async_aws_s3
    #     [8 ] oneup_flysystem.adapter_factory.awss3v2
    #     [9 ] oneup_flysystem.adapter_factory.awss3v3
    #     [10] oneup_flysystem.adapter_factory.azureblob
    #     [11] oneup_flysystem.adapter_factory.dropbox
    #     [12] oneup_flysystem.adapter_factory.googlecloudstorage
    #     [13] oneup_flysystem.adapter_factory.rackspace
    #     [14] oneup_flysystem.adapter_factory.webdav
    #     [15] oneup_flysystem.adapter_factory.ftp
    #     [16] oneup_flysystem.adapter_factory.sftp
    #     [17] oneup_flysystem.adapter_factory.gridfs
    #     [18] oneup_flysystem.adapter_factory.customadapter
    #     [19] oneup_flysystem.adapter_factory.memory
    #     [20] oneup_flysystem.adapter_factory.fallback
    #     [21] oneup_flysystem.adapter_factory.gaufrette
    #     [22] oneup_flysystem.adapter_factory.replicate
    #     [23] oneup_flysystem.cache_factory.adapter
    #     [24] oneup_flysystem.cache_factory.memory
    #     [25] oneup_flysystem.cache_factory.noop
    #     [26] oneup_flysystem.cache_factory.memcached
    #     [27] oneup_flysystem.cache_factory.php_redis
    #     [28] oneup_flysystem.cache_factory.predis
    #     [29] oneup_flysystem.cache_factory.stash
    #     [30] oneup_flysystem.cache_factory.psr6
    #     [31] oneup_flysystem.adapter.local
    #     [32] oneup_flysystem.adapter.cached
    #     [33] oneup_flysystem.adapter.nulladapter
    #     [34] oneup_flysystem.adapter.memory
    #     [35] oneup_flysystem.adapter.zip
    #     [36] oneup_flysystem.adapter.async_aws_s3
    #     [37] oneup_flysystem.adapter.awss3v2
    #     [38] oneup_flysystem.adapter.awss3v3
    #     [39] oneup_flysystem.adapter.azureblob
    #     [40] oneup_flysystem.adapter.dropbox
    #     [41] oneup_flysystem.adapter.googlecloudstorage
    #     [42] oneup_flysystem.adapter.rackspace
    #     [43] oneup_flysystem.adapter.webdav
    #     [44] oneup_flysystem.adapter.ftp
    #     [45] oneup_flysystem.adapter.sftp
    #     [46] oneup_flysystem.adapter.gridfs
    #     [47] oneup_flysystem.adapter.fallback
    #     [48] oneup_flysystem.adapter.gaufrette
    #     [49] oneup_flysystem.adapter.replicate
    #     [50] oneup_flysystem.mount_manager
    #     [51] oneup_flysystem.filesystem
    #     [52] oneup_flysystem.cache.adapter
    #     [53] oneup_flysystem.cache.memory
    #     [54] oneup_flysystem.cache.noop
    #     [55] oneup_flysystem.cache.memcached
    #     [56] oneup_flysystem.cache.predis
    #     [57] oneup_flysystem.cache.php_redis
    #     [58] oneup_flysystem.cache.stash
    #     [59] oneup_flysystem.cache.psr6
    #     [60] oneup_flysystem.plugin.empty_dir
    #     [61] oneup_flysystem.plugin.get_with_metadata
    #     [62] oneup_flysystem.plugin.list_files
    #     [63] oneup_flysystem.plugin.list_paths
    #     [64] oneup_flysystem.plugin.list_with
    #     [65] oneup_flysystem.public_uploads_adapter_adapter
    #     [66] oneup_flysystem.public_uploads_filesystem_filesystem
    #     [67] League\Flysystem\Filesystem
    #     [68] League\Flysystem\FilesystemInterface $publicUploadsFilesystem
    #     > 67
    #
    #
    #     // This service is a public alias for the service
    #     // oneup_flysystem.public_uploads_filesystem_filesystem
    #
    #     Information for Service "oneup_flysystem.public_uploads_filesystem_filesystem"
    #     ==============================================================================
    #
    #     ---------------- -------------------------------------------------------------
    #     Option           Value
    #     ---------------- -------------------------------------------------------------
    #     Service ID       oneup_flysystem.public_uploads_filesystem_filesystem
    #     Class            League\Flysystem\Filesystem
    #     Tags             oneup_flysystem.filesystem (key: public_uploads_filesystem)
    #     Public           no
    #     Synthetic        no
    #     Lazy             no
    #     Shared           yes
    #     Abstract         no
    #     Autowired        no
    #     Autoconfigured   no
    #     ---------------- -------------------------------------------------------------
    #     There it is: oneup_flysystem.public_uploads_filesystem_filesystem. T
    #     That service was created thanks to our config and we'll use it soon in UploaderHelper.
    #     The bundle also created another service called: League\Flysystem\Filesystem.
    #     Well, actually, it's an alias:
    #     I'll type 61 to view more info about it.
    #     Yep! This points to our public_uploads_filesystem service.
    #     The purpose of this is that it allows us to type-hint League\Flysystem\Filesystem and Symfony will autowire our filesystem service.
    #     If you only have 1 filesystem, having this alias is great.
    #     But if you have multiple, well, you can only autowire one of them.
    #     I'm going to remove the alias -
    #     I'll show you another way to access the filesystem service.
    #     Ok, config done!
    #     Next, let's start using this shiny new Filesystem service.
    # Anyways, remove that bind and try the fixtures again:
    # php bin/console doctrine:fixtures:load
    # This is the error I was waiting for.
    # “Cannot autowire service UploaderHelper argument $filesystem of __construct() references FilesystemInterface but no such service exists.”
    # There are two ways to fix this.
    # First, we could re-add the alias option and point it at this FilesystemInterface:

        # But for now, a great solution is to create a private filesystem.
        # Open the config/packages/oneup_flysystem.yaml file.
        # Copy the public_uploads_adapter,
        # paste and call it private_uploads_adapter.
        # You can store the files anywhere, as long as it's not in public/.
        # But, the var/ directory is sort of meant for this type of thing.
        # So let's say: var/uploads.
        # Oh, and I could re-use my uploads_dir_name parameter here -
        # but it won't give us any benefit.
        # That parameter is really meant to keep the upload directory and public path to assets in sync.
        # But these files won't have a public path anyways, we'll make them downloadable in an entirely different way.
        private_uploads_adapter:
            local:
                directory: '%kernel.project_dir%/var/uploads'
    filesystems:
        public_uploads_filesystem:
            adapter: public_uploads_adapter
            # alias: League\Flysystem\Filesystem
            # Or, we can create a new bind.
            # I'll do the second, because it works better if you have multiple filesystem services, which we will soon.
        # Next, for filesystems, do the same thing:
        # make a private_uploads_filesystem that will use the private_uploads_adapter.
        private_uploads_filesystem:
            adapter: private_uploads_adapter