framework:
    router:
        strict_requirements: ~
        # In Symfony 5.1, instead of setting these 2 parameters,
        # you can set 1 new piece of config:
        default_uri: 'http://127.0.0.1:8000/'
