[program:messenger-consume]
command=php /Users/khalil.rais/cauldron_overflow//bin/console messenger:consume async_priority_high async --time-limit=3600
user=khalil
numprocs=2
autostart=true
autorestart=true
process_name=%(program_name)s_%(process_num)02d
#The file tells Supervisor which command to run
#and other important info like which user it should run the process
#and the number of processes to run.
#This will create two worker processes.
#The more workers you run,
#the more messages can be handled at once.
#But also, the more memory & CPU you'll need.