# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    cache_adapter: cache.adapter.apcu
    locale: 'en'
    # It's not a huge problem,
    # but repetition is a bummer
    # and this will cause some issues when moving to S3:
    # we'll need to hunt down all of these paths
    # and change them to point to the S3 domain.
    # Let's tighten this up.
    # In services.yaml, create two new parameters:
    # The first will be uploads_dir_name set to uploads -
    # this is the name of the directory where we are storing uploaded files.
    # Call the second one uploads_base_url and set this to almost the same thing:
    # / and then %uploads_dir_name%. This represents the base URL to the uploaded assets.
    uploads_dir_name: 'uploads'
    # So if our system is working so awesomely,
    # why don't the images show up?
    # It's because of the hostname in front of the images:
    # it's pointing at our local server,
    # but it should be pointing at S3.
    # Click any of the images on S3.
    # Here it is: every object in S3 has its own, public URL.
    # Well actually, every object has a URL,
    # but whether or not anyone can access that URL is another story.
    # More on that later.
    # I'm going to copy the very beginning of that,
    # and then go open services.yaml.
    # Earlier, we created a parameter called uploads_base_url.
    # LiipImagineBundle uses this to prefix every URL that it renders.
    # The current value includes 127.0.0.1:8000
    # because that's our SITE_BASE_URL environment variable value.
    # That worked fine when things were stored locally but not anymore!
    # Change this to https://s3.amazonaws.com/
    # and then our bucket name, which is already available as an environment variable: %env()%,
    # then go copy AWS_S3_ACCESS_BUCKET, and paste.
    uploads_base_url: '%https://s3.amazonaws.com/%env(AWS_S3_BUCKET_NAME)%'
    # This is our new base URL.
    # What about the uploads_dir_name parameter?
    # We're not using that at all anymore! Trash it.
    # Ok, let's try it! Refresh and it actually works!
    # I mean of course, it works!
    # And just like that - every single path to every single uploaded asset will now be absolute.
    # Seriously! Test it out! Boom! Both the link href and the image src contain the https://localhost:8000 part.
    # And, sure, you could add some config so
    # that you could turn this on only when you need it,
    # but I don't really see the point.
    # I'll keep absolute URLs always.
    # Next: let's start uploading private assets:
    # stuff that can't be put into the public/ directory
    # because we need to check security before we let a user download it.
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

        # setup special, global autowiring rules
        bind:
            $markdownLogger: '@monolog.logger.markdown'
            $isDebug: '%kernel.debug%'
            # Let's take it for a test drive! Go back, refresh the form and it works!
            # Naw, I'm kidding - we knew this error was coming but isn't it beautiful?
            # “Cannot resolve argument $uploadHelper of the edit() method:
            # Cannot autowire service UploadHelper:
            # argument $uploadsPath of method __construct() is type-hinted string,
            # you should configure its value explicitly.
            # ”
            # That's programming poetry people!
            # And it makes sense: autowiring doesn't work for scalar arguments.
            # We got this: open config/services.yaml.
            # We could configure the specific argument for this specific service.
            # But if you've watched our Symfony series,
            # you know that I like to use the bind feature.
            # The argument name is $uploadsPath.
            # So, below _defaults and bind,
            # add $uploadsPath set to %kernel.project_dir%/public/uploads.
            # “Unused binding $uploadsPath in service UniqueUserValidator.”
            # This is a bad error message from Symfony, at least the second half of the message.
            # A minute ago, we had an argument here called $uploadsPath.
            # Open up config/services.yaml.
            # Ah, that worked because we have $uploadsPath configured as a global bind.
            # And when you configure a bind, it must be used in at least one place in your app.
            # If it's not used anywhere, you get this error.
            # It's kinda nice: Symfony is saying:
            # “Hey! You configured this bind but you're not using it - are you maybe messing something up on accident?”
            # The UniqueUserValidator part of the message is really a bug in the error message,
            # which makes this a bit confusing.

            # Then, under bind, set $publicUploadFilesystem to the filesystem service id -
            # you can see it in the error.
            # It suggests two services that implement the FilesystemInterface type-hint -
            # we want the second one. Type @ then paste.
            # And in services.yaml, update the "bind" in the same way.
            # Hmm, and I think I'll change the argument name it's binding to: just $uploadFilesystem.

            # That will break UploaderHelper:
            # we need to rename the argument there.
            # But, let's just see what happens if we "forget" to do that.
            # Refresh the page:“Unused binding $uploadFilesystem in S3Client.”
            #
            # This is that generic and somewhat "inaccurate" error that says
            # that we've configured a bind that's never used!
            # The error is even better if we temporarily delete the bind entirely.
            # Ah, here it is:
            # “Cannot autowire UploaderHelper:
            # argument $publicUploadFilesystem references an interface,
            # but that interface cannot be autowired.”
            # This is saying: Hey! I don't know what you want me to send for this argument!
            # Put the bind back, then, in UploaderHelper here it is.
            $uploadsFilesystem: '@oneup_flysystem.uploads_filesystem_filesystem'
            # One more time for the fixtures!
            # php bin/console doctrine:fixtures:load
            # > yes
            #
            # > purging database
            # > loading App\DataFixtures\TagFixture
            # > loading App\DataFixtures\UserFixture
            # > loading App\DataFixtures\ArticleFixtures
            # > loading App\DataFixtures\CommentFixture
            # Ok, no error! Check out the public/uploads/ directory.
            # Yes! We have files! Refresh the homepage.
            # We are good! We still need to tweak a few more details,
            # but our app is now way more ready to work locally or in the cloud.
            # Cool! But, Symfony will not be able to autowire this string argument. You can see the error if you
            # try to reload any page. Yep!
            # We know how to fix that: back in services.yaml, add a bind: $uploadedAssetsBaseUrl
            # set to %uploads_base_url%. Now... it works!
            $uploadedAssetsBaseUrl: '%uploads_base_url%'
            # Next, in services.yaml, because there's no private_upload_filesystem anymore,
            # remove that bind.

    # custom aliases for autowiring
    Nexy\Slack\Client: '@nexy_slack.client'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Form\TypeExtension\TextareaSizeExtension:
        tags:
            - { name: form.type_extension,
                extended_type: Symfony\Component\Form\Extension\Core\Type\TextareaType }
    # Try it! Oh... wow - huge error!
    # This RequestStackContext service is such a low-level service,
    # that Symfony doesn't make it available to be used for autowiring.
    # Check out the error, it says: “Yo! You can't autowire the $requestStackContext argument:
    # it's type-hinted with a class called RequestStackContext,
    # but there isn't a service with this id.
    # Maybe you can create a service alias for this class that points to the assets.context service.”
    # This is a bit technical and we talk about this in our Symfony Fundamentals course.
    # Symfony sees that the RequestStackContext type-hint is not autowireable,
    # but it also sees that there is a service in the container - called assets.context -
    # that is an instance of this class!
    # Check it out: copy the full class name and then go into config/services.yaml.
    # At the bottom, paste the full class name, go copy the service id they suggested, and say @assets.context.
    Symfony\Component\Asset\Context\RequestStackContext: '@assets.context'
    # This creates a service alias.
    # Basically, there is now a new service that lives in the container called Symfony\Component\Asset\Context\RequestStackContext.
    # And if you fetch it, it'll really just give you the assets.context service.
    # The key thing is that this makes the class autowireable.
    # To prove it, find your terminal and run to search for all autowireable classes that contain that string. :
    #
    # php bin/console debug:autowiring request
    # Autowirable Types
    # =================
    #
    # The following classes & interfaces can be used as type-hints when autowiring:
    # (only showing classes/interfaces matching request)
    #
    # Factory for PSR-7 Request.
    # Http\Message\RequestFactory (httplug.message_factory.default)
    #
    # Psr\Log\LoggerInterface $requestLogger (monolog.logger.request)
    #
    # Uses a RequestStack to populate the context.
    # Symfony\Component\Asset\Context\RequestStackContext (assets.context)
    #
    # Request stack that controls the lifecycle of requests.
    # Symfony\Component\HttpFoundation\RequestStack (request_stack)
    #
    # Holds information about the current request.
    # Symfony\Component\Routing\RequestContext (router.request_context)
    #
    # Symfony\Component\Routing\RequestContextAwareInterface (router.default)
    #
    # Hey! There is our RequestStackContext!
    # If we had run this a minute ago, it would not have been there.
    # Refresh the page now. Got it! And if you look at the path, yep!
    # It's /uploads/article_image/astronaut.jpeg.
    # If we lived under a subdirectory,
    # that subdirectory would be there.
    # Small detail, but our site is still super portable.
    # Next, let's create thumbnails of our image so the user doesn't need to download the full size.
    # Let's close all these tabs so we can concentrate.
    # Open config/services.yaml and,
    # at the bottom, paste that config!
    # But I'm going to simplify this:
    # copy the class name, remove it,
    # and paste that as the service id.
    # Why? First, because, when possible,
    # it's just easier to use the class name as the service id instead of inventing a string id. A
    # nd second, this will allow us to autowire the S3Client service into any of our services or controllers.
    # We won't need that for what we're doing, but it's nice.
    Aws\S3\S3Client:
        arguments:
            # This takes just one argument: a big array of config.
            -
                # This old looking API version is actually still the most recent.
                version: '2006-03-01' # or 'latest'
                # For region, this depends on what region you chose for your bucket.
                # Mine is us-east-1 because I selected Virginia.
                # If you selected a different region, it won't work. Kidding!
                # Just do some Googling to find the right region id.
                region: "region-id" # 'eu-central-1' for example
                credentials:
                    # What about the key and secret?
                    # These are the values IAM gave us after creating the user.
                    # But, we probably don't want to put their values right here
                    # and commit them to the repository.
                    # key: "s3-key"
                    # secret: "s3-secret"

                    # If you want, you could copy the values
                    # and put them directly into this file.
                    # But remember, the .env file is committed to your git repository
                    # and you really don't want any secret value to be committed.
                    # Instead, create a new file at the root of your app called .env.local.
                    # This file is also read by Symfony and any values will override the ones in .env.
                    # It's also ignored from git via our .gitignore file.
                    # Copy the two keys from .env and paste them here.
                    # And now we can grab the real values. Copy
                    # the id, paste, then show the secret, copy, and paste that.
                    # Environment variables, set!
                    # To use them, head back to services.yaml.
                    # Replace the key with the special environment variable syntax: %env()% and inside,
                    # AW... go copy the name - AWS_S3_ACCESS_ID.
                    # Re-use that syntax for the secret: AWS_S3_ACCESS_SECRET.
                    key: '%env(AWS_S3_ACCESS_ID)%'
                    secret: '%env(AWS_S3_ACCESS_SECRET)%'
                    # If you forget about Flysystem for a minute,
                    # we now have a fully functional S3Client service
                    # that we can autowire and use to do anything with our new bucket!
                    # The question now is: how can we tell Flysystem to use this?