# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    cache_adapter: cache.adapter.apcu
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

        # setup special, global autowiring rules
        bind:
            $markdownLogger: '@monolog.logger.markdown'
            $isDebug: '%kernel.debug%'
            # Let's take it for a test drive! Go back, refresh the form and it works!
            # Naw, I'm kidding - we knew this error was coming but isn't it beautiful?
            # “Cannot resolve argument $uploadHelper of the edit() method:
            # Cannot autowire service UploadHelper:
            # argument $uploadsPath of method __construct() is type-hinted string,
            # you should configure its value explicitly.
            # ”
            # That's programming poetry people!
            # And it makes sense: autowiring doesn't work for scalar arguments.
            # We got this: open config/services.yaml.
            # We could configure the specific argument for this specific service.
            # But if you've watched our Symfony series,
            # you know that I like to use the bind feature.
            # The argument name is $uploadsPath.
            # So, below _defaults and bind,
            # add $uploadsPath set to %kernel.project_dir%/public/uploads.
            $uploadsPath: '%kernel.project_dir%/public/uploads'
            # This means: anywhere that $uploadsPath is used as an argument for a method
            # that's autowired - usually a controller action or the constructor of a service -
            # pass in this value.


    # custom aliases for autowiring
    Nexy\Slack\Client: '@nexy_slack.client'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Form\TypeExtension\TextareaSizeExtension:
        tags:
            - { name: form.type_extension,
                extended_type: Symfony\Component\Form\Extension\Core\Type\TextareaType }
